exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
  "test",
  "tests",
]

line-length = 90
indent-width = 4

[lint]
select = ["ALL"]
ignore = [
  "COM812",  # Missing trailing comma - IGNORE
  "TRY003",  # Avoid specifying long messages outside the exception class
  "EM101",   # Exception must not use a string literal, assign to variable first
  "FBT001",  # type hint positional argument - bool is not allowed - IGNORE
  "FBT003",  # Bool positional argument - IGNORE
  "TD002",   # Todo error - IGNORE
  "TD003",   # Todo error - IGNORE
  "FIX002",  # Fixme error - IGNORE
  "FBT002",  # boolean-default-value-positional-argument - IGNORE
  "INP001", # Implicit Namespace error  - IGNORE
  "TC003",  # Bug in TYPE_CHECKING recommendation for dataclasses - IGNORE
  "D102",  # Missing docstring in public method - HANDLED BY flake8-docstrings
  # "Q000", # Quotes


]
# Todo: Add exception classes EM102, BLE001, EM101
# Todo: Fix import sorting issue I001
unfixable = ["B"]

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[lint.per-file-ignores]
"vesync.py" = ["F403"]
"**/models/*" = ["N804", "N803", "ANN401", "N802", "N815"]
"vesyncbulb.py" = ["PLR2004"]
"**/errors.py" = ["S105"]
"testing_scripts/device_configurations.py" = ["T201"]

[lint.pep8-naming]
extend-ignore-names = ["displayJSON"]

[lint.pydocstyle]
convention = "google"

[lint.pylint]
max-public-methods = 30
max-args = 6

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "cr-lf"
