name: Run Linting and Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check --output-format=github --target-version=py311 src/pyvesync
        continue-on-error: true
      - name: Run pylint
        run: |
          pip install pylint
          pylint src/pyvesync --output-format=text --reports=n
        continue-on-error: true
      - name: Test with pytest
        run: |
          pip install pytest
          pytest -v -s
        continue-on-error: true
