name: Run Linting and Unit Tests

on:
  pull_request:
    branches:
      - master
      - dev
  push:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint with Ruff
        id: ruff
        run: |
          pip install ruff
          ruff check --output-format=github src/pyvesync
        continue-on-error: true
      - name: Run pylint
        id: pylint
        run: |
          pip install pylint
          pylint src/pyvesync --output-format=text --reports=n
        continue-on-error: true
      - name: Test with pytest
        id: pytest
        run: |
          pip install pytest
          pytest -v
      - name: Fail if any steps failed
        run: |
          [ "${{ steps.ruff.outcome }}" == "failure" ] || [ "${{ steps.pylint.outcome }}" == "failure" ] || [ "${{ steps.pytest.outcome }}" == "failure" ] && exit 1 || exit 0
